version: '3.4'

volumes:
  lighthouse_data:
  prysm_data:
  lodestar_data:
  config_data:
  teku_data:

x-prysm-beacon-node-env: &prysm-bn-env
  TRACING_ENDPOINT: http://jaeger-tracing:14268/api/traces
  PROCESS_NAME: beacon-node
  VERBOSITY: debug
  P2P_TCP_PORT: 13000
  MIN_SYNC_PEERS: 0

x-prysm-beacon-node: &prysm-bn
  depends_on:
    jaeger-tracing:
      condition: service_started
    genesis-generator:
      condition: service_completed_successfully
  image: inphi/prysm:eip4844-f08af1
  healthcheck:
    test: ["CMD", "curl", "--fail", "localhost:3500/eth/v1/node/health"]
    interval: 2s
    timeout: 2s
    retries: 40
    start_period: 1s
  entrypoint: run_beacon_node.sh
  volumes:
    - './config_data:/config_data'
    - type: bind
      source: ./prysm/run_beacon_node.sh
      target: /usr/local/bin/run_beacon_node.sh

services:
  genesis-generator:
    image: inphi/ethereum-genesis-generator:eip4844
    entrypoint: run_genesis_generator.sh
    volumes:
      - ./shared/run_genesis_generator.sh:/usr/local/bin/run_genesis_generator.sh
      - ./shared/genesis-generator-configs:/config
      - ./shared/generated-configs:/gen-configs
      - lighthouse_data:/lighthouse_data
      - prysm_data:/prysm_data
      - lodestar_data:/lodestar_data
      - teku_data:/teku_data
      - ./config_data:/data

  prysm-beacon-node:
    <<: *prysm-bn
    depends_on:
      nethermind:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    environment:
      <<: *prysm-bn-env
      EXECUTION_NODE_URL: http://nethermind:8551
      PROCESS_NAME: beacon-node
      MIN_SYNC_PEERS: 0
    ports:
      - '3500:3500'
      - '4000:4000'
      - '13000:13000'

  prysm-validator-node:
    depends_on:
      prysm-beacon-node:
        condition: service_started
      jaeger-tracing:
        condition: service_started
      genesis-generator:
        condition: service_completed_successfully
    image: inphi/prysm:eip4844-f08af1
    command: >
      validator
      --accept-terms-of-use
      --beacon-rpc-provider prysm-beacon-node:4000
      --rpc
      --grpc-gateway-host 0.0.0.0
      --grpc-gateway-port 7500
      --force-clear-db
      --chain-config-file=/config_data/custom_config_data/config.yaml
      --suggested-fee-recipient 0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b
      --wallet-password-file=/prysm_data/wallet_pass.txt
      --wallet-dir=/prysm_data/wallet
      --enable-tracing
      --tracing-endpoint http://jaeger-tracing:14268/api/traces
      --tracing-process-name validator-node
    ports:
      - '7500:7500'
    volumes:
      - './config_data:/config_data'
      - 'prysm_data:/prysm_data'

  nethermind:
    image: nethermindeth/nethermind:eip-4844-v4
    depends_on:
      genesis-generator:
        condition: service_completed_successfully
    ports:
      - '8545:8545'
    entrypoint: 'nethermind.sh'
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:8545"]
      interval: 2s
      timeout: 2s
      retries: 40
      start_period: 1s
    volumes:
      - './config_data:/config_data'
      - type: bind
        source: ./nethermind/nethermind.sh
        target: /usr/local/bin/nethermind.sh

  jaeger-tracing:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
